title: Emily Brown
author: Emily Brown
subtitle: Oakland-based writer and poet.
description: Emily Brown is an Oakland-based writer with background in songwriting and poetry. I write brand copy, product education content, and long-form arts and culture interviews.

url: "https://emilycolleenbrown.com"
baseurl: ""

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Portfolio ☙"
   link: "portfolio"
 - name: "Resume ⤓"
   absolute-link: "https://emilycolleenbrown.com/assets/EmilyBrown—Resume.pdf"

footer:
 - name: "Twitter"
   absolute-link: "https://twitter.com/emilybrownmusic"
 - name: "Instagram"
   absolute-link: "https://instagram.com/emilybrownmusic"
 - name: "Email"
   absolute-link: "mailto:Emilycolleenbrown@gmail.com"
