title: Emily Brown
author: Emily Brown
subtitle: Oakland-based writer and poet.

url: "https://emilycolleenbrown.com"
baseurl: ""

footer_only_homepage: true
footer_url: ""
footer_text: ""

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://rahulbothra.com/cv.pdf"
